spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
