spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cotbbtqcn0vc738m30a0-a:5432/anamnese
    username: useradmin
    password: Qy9PPdI91O99ipSDAgCySiSTX8MszEqp
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
